### ISSUE TITLE
Server side rendered b-modal causes runtime error

### ISSUE THREAD

**Issue by JamieLottering** [bootstrap-vue/bootstrap-vue#1195]
Using Nuxt with our app and some pages simply output a modal, as seen with #1167 .

These pages render modals on the server side and default to `visible` as such:

```
<b-modal visible>
   Some content
</b-modal>
```

However this causes a runtime error in dev because the server side html doesn't match the client side html. It looks like it may be caused by the close button in the header.

This is a screenshot of the error.
![screenshot](https://www.dropbox.com/s/jth1rkt6tb5l8cc/Screen%20Shot%202017-10-12%20at%203.23.11%20PM.png?raw=1)

Now of course wrapping these in a `<no-ssr />` tag works fine but this is not ideal as I'd like the HTML for these to be visible in the initial source.

I'm not sure if this bug is specific to bootstrap-vue or an error in Vue itself.

**Comment by JamieLottering** [comment]
FWIW If I add the `hide-header-close` prop on the `<b-modal />` it renders correctly without an error. But this is not the behavior I want.

In addition, manually putting a 
`<button type="button" name="button">&times;</button>` in the modal body slot it doesn't experience this client/server html mismatch so it must be something in the `<b-modal />` itself causing this.

**Comment by tmorehouse** [comment]
This has been fixed in the latest dev branch already.

**Comment by JamieLottering** [comment]
I’m curious what the fix was for that then. I still see the hard coded x symbol in button-close on dev.

**Comment by JamieLottering** [comment]
Never mind. Just saw your other comment. Thanks!!
