### ISSUE TITLE
[1.0.0] SSR mismatch with b-popover and b-modal

### ISSUE THREAD

**Issue by JamieLottering** [bootstrap-vue/bootstrap-vue#1296]
VueJS version: 2.5.3
Bootstrap-vue version: 1.0.0

`<b-popover />` and `<b-modal />` are causing mismatch errors when rendered server side. They both appear to be inserting an extra text node with empty content.

Here's an example of an error generated when including the following in a template that is rendered server side:
`<b-popover><p>Hello World</p></b-popover>`
[Screenshot of error generated above](https://www.dropbox.com/s/5gbn6b5z87dfh7v/Screen%20Shot%202017-11-06%20at%203.07.17%20PM.png?raw=1)

And then here is an example that is caused by the following server rendered content:
`<b-modal visible><p>Hello World</p></b-modal>`
[Screenshot of modal err](https://www.dropbox.com/s/u5d75uq2vq4cf1j/Screen%20Shot%202017-11-06%20at%203.09.48%20PM.png?raw=1)

**Comment by tmorehouse** [comment]
Thanks for the report.

The modal one appears to be related to the previous bug for the b-button-close (where `&times;` was being converted client side to the UTF-8 `×` , although that issue was corrected in v1.0.0.

Would you happen to be running this behinds a caching system (such as CloudFlare) that minifies the HTML before delivering the final content to the client?

**Comment by tmorehouse** [comment]
If you use an earlier version of Vue (say 2.4x), does the issue still appear?

**Comment by JamieLottering** [comment]
Nope, not running any kind of cache or HTML minifier, just using NUXT to serve everything. Yes the issue still appears with using Vue 2.4.4.

Not sure if this is helpful but heres a diff (the left is what I see from 'view source' and the right is what happens if I wrap it in a <no-ssr> tag and copy the HTML after it is mounted)

https://www.diffchecker.com/BTO1BZWM

**Comment by tmorehouse** [comment]
The `aria-*` and `id` attributes are added on mounted() on client side (if no id prop is provided, otherwise added on both client/server when provided), so those diffs are OK.

Which version of nuxt?  I just ran a test on nuxt 1.0.0.rc.11 but couldn't replicate.

**Comment by tmorehouse** [comment]
For modal, if you provide a unique ID (set the prop `id` to some value) does it still puke?

**Comment by JamieLottering** [comment]
Yep. nuxt 1.0.0.rc.11 is what we are using.

Just tested with an id and still no go. I'm not sure why it's seeing an empty text node in between the h5.modal-title and button.close. This happens even if I pass `hide-header-close` to the <b-modal />

**Comment by tmorehouse** [comment]
This is odd for sure...  The templates for both modal and b-popover haven't changed much since beta.9 (modal has one extra DIV wrapper now for handling lazy modal $refs).

Are you using any additional Vue plugins or directives?

**Comment by tmorehouse** [comment]
Also, which browser are you using? And does the error appear in a different browser?  I tested in Firefox.

**Comment by tmorehouse** [comment]
And, another question.  are you importing components individually or using the full Bootstrap-Vue lib?

**Comment by JamieLottering** [comment]
We are using the following packages that bring in some components:
vue-gmaps, vee-validate, v-mask, vuejs-datepicker and then also using vue-i18n. I tested this in latest version of Firefox & Chrome. 

We are importing components wholesale 

```
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue'

Vue.use(BootstrapVue)
```

**Comment by tmorehouse** [comment]
vee-validate can cause  few issues if the defaults aren't modified (but they produce a different error about duplicate props/computedprops))

**Comment by JamieLottering** [comment]
Well we also use the injection mode of Vee-validate so you have to explicitly include it in the components you want to use it for, in this case we aren't so it doesn't inject any properties.

**Comment by tmorehouse** [comment]
Could you provide a basic sample modal/popover markup that you are using?

I'll create a Nuxt SSR mockup on my server and test.

**Comment by JamieLottering** [comment]
This is basically what our login page looks like (although in reality it includes a LoginModal component that wraps some common functionality specific to us). I removed all the extraneous stuff just to see if I could get b-modal to work and still has the issue.

```
<template>
  <b-modal visible title="hello world" hide-header-close>
    <p>Hello World</p>
  </b-modal>
</template>

<script>
export default {
  head () {
    return {
      title: 'Login'
    }
  }
}
</script>
```

**Comment by JamieLottering** [comment]
[I'm actually able to see the empty text node in between modal-title and the button when I view source](https://www.dropbox.com/s/qf5hvv8me9fw9dr/Screen%20Shot%202017-11-06%20at%204.14.31%20PM.png?raw=1)
Where the heck is that coming from...

**Comment by tmorehouse** [comment]
Just pasted the following:

```html
  <b-modal visible title="hello world" hide-header-close>
    <p>Hello World</p>
  </b-modal>
```
in one of my SSR rendered pages, and no issues appear in the console (both firefox and chrome)

**Comment by JamieLottering** [comment]
You're running in dev mode right? AFAIK prod mode will swallow those mismatch errors

**Comment by tmorehouse** [comment]
Yep, running server in dev mode.

**Comment by tmorehouse** [comment]
What is interesting, is that Vue-loader (and vue-template-compiler) usually removes most whitespace from templates (when not inside certain tags).

Viewing the rendered source I do see a single white space character in there after the closing `</h5>` tag:

```html
<header class="modal-header"><h5 class="modal-title">hello world</h5> <!----></header>
```
But Vue isn't barfing and complaints.

**Comment by JamieLottering** [comment]
Interesting. What version of vue-loader are you on? We are using 13.4.0

**Comment by JamieLottering** [comment]
Well I was hoping that would be it but even vue-loader 13.0.4 causes an issue for us

**Comment by tmorehouse** [comment]
13.3.0

**Comment by tmorehouse** [comment]
Just ran `yarn upgrade` to see if that changed anything, and still no complaints about the space/text-node.

**Comment by tmorehouse** [comment]
And here is my dependencies for reference:
```js
  "dependencies": {
    "accept-language": "^3.0.17",
    "axios": "^0.16.2",
    "bluebird": "^3.5.0",
    "bootstrap": "^4.0.0-beta.2",
    "bootstrap-vue": "^1.0.0",
    "chart.js": "^2.7.0",
    "cross-env": "^5.0.1",
    "express": "^4.15.3",
    "font-awesome": "^4.7.0",
    "full-icu": "^1.2.0",
    "hashids": "^1.1.1",
    "locale-compare-polyfill": "0.0.2",
    "lodash.groupby": "^4.6.0",
    "moment": "2.18.1",
    "moment-timezone": "^0.5.13",
    "nuxt": "^1.0.0-rc11",
    "promise-mysql": "^3.1.0",
    "source-map-support": "^0.4.15",
    "vue": "^2.5.2",
    "vue-awesome": "^2.3.3",
    "vue-chartjs": "^2.8.7",
    "vue-i18n": "^7.3.0",
    "vue-kindergarten": "^0.3.2",
    "vue-server-renderer": "^2.5.2",
    "vue-social-sharing": "^2.2.10",
    "vue-template-compiler": "^2.5.2",
    "vuex": "^2.5.0"
  },
```

**Comment by JamieLottering** [comment]
Thanks for the help so far. I'm at a loss now, it's probably not anything to do with bootstrap-vue itself but more likely something on our side. I'll have to keep digging until I find something. Maybe someone else will chime in with the same issue in the meantime.

**Comment by JamieLottering** [comment]
Ok so now I'm not totally convinced it's a problem with our project.

I just created a new nuxt project using vue cli
`vue init nuxt-community/starter-template bootstrap-modal`

and then installed Bootstrap and BoostrapVue. Still same exact issue when rendering a modal through server side. I have a repo [here](https://github.com/JamieLottering/bootstrap-vue-modal-bug) if you want to clone it and try it yourself. I'd be curious to see what happens for you.

**Comment by tmorehouse** [comment]
Using the above repo, I cn confirm the modal is bailing on SSR.

The only difference I can see (so far) from my test server is that I m using backpack to run the dev server.

**Comment by JamieLottering** [comment]
Glad to hear you were able to reproduce it as well. We use backpack as well on our project, so I'm not sure if that's the culprit

**Comment by tmorehouse** [comment]
I removed the white space from the template (between the closing `</h5>` tag an the enxt tag in hte BSVue template and the issue still persists.

As a test, I went into `node_modules/boot-strap-vue/package.json` and edited out the `main` and `jsnext` entries (which point to the ES modules) so that it would use hte `esm.js`  version (in dist) and all worked without any SSR bails.

Loking at the generated es module files (in the `/es` dir), the templates are identical (.vue files in /src and /es)

So it looks like it might be leaning towards needing some vue loader tweaks to nuxt.config.js

**Comment by tmorehouse** [comment]
Try changing your `plugins/bootstrap.js` file to the following (to use the fully compiled esm file):

```js
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue/dist/bootstrap-vue.esm'

Vue.use(BootstrapVue)
```

**Comment by JamieLottering** [comment]
Yep, that fixes it. Thanks so much for your help in tracking this down!!

**Comment by JamieLottering** [comment]
Thanks @tmorehouse and @pi0 !!
