### ISSUE TITLE
Navbar component auto toggle when I click on Navbar dropdown item in shorten mode

### ISSUE THREAD

**Issue by tienv2i** [bootstrap-vue/bootstrap-vue#1474]
I have a simple code for navbar:
```
<b-navbar toggleable="md" type="dark" variant="info">
    <b-navbar-brand href="#">MIINODE</b-navbar-brand>
    <b-navbar-toggle target="nav_collapse"></b-navbar-toggle>
    <b-collapse is-nav id="nav_collapse">
      <b-navbar-nav>
        <b-nav-item href="#">Link</b-nav-item>
        <b-nav-item href="#" disabled>Disabled</b-nav-item>
      </b-navbar-nav>
      <b-navbar-nav class="ml-auto">
        <b-nav-item-dropdown right>
            <template slot="button-content">
              <em>User</em>
            </template>
            <b-dropdown-item href="#">Profile</b-dropdown-item>
            <b-dropdown-item href="#">Signout</b-dropdown-item>
          </b-nav-item-dropdown>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
```
It works well on Desktop mode, but when I change to md screen, I can't expand the navbar dropdown item, the navbar auto close when I click on the dropdown menu.
You can see the error in the image: [http://gph.is/2CLXEgQ](http://gph.is/2CLXEgQ)

**Comment by tmorehouse** [comment]
Interesting, this appears to only happen when the user doesn't click directly on the dropdown's toggle text (clicking to the right of it causes the collapse to close)

**Comment by dominicbarnes** [comment]
I'm glad there's a fix merged, but I hope it gets released soon.

**Comment by pi0** [comment]
Should be fixed in v1.4.1.

**Comment by DaleMckeown** [comment]
@pi0 This still appears to be an issue in the latest version.

Here's an example from the docs:

![collapse-bug](https://user-images.githubusercontent.com/1249673/38167670-ec8fbc22-3530-11e8-8983-c1fa353b43e1.gif)

**Comment by Velikolay** [comment]
I can still reproduce this, is there a known workaround solution?
