### ISSUE TITLE
<b-form-input> Change event not firing in IE11

### ISSUE THREAD

**Issue by Giwayume** [bootstrap-vue/bootstrap-vue#2124]
This simple example of listening to the change event of the input does not work in IE11.

Using version 2.0.0-rc.11

Sample .vue file:
```
<template>
    <b-form-input @change="onChange($event)"></b-form-input>
</template>
<script>
    export default {
        methods: {
            onChange: function(e) {
                alert('something changed!');
            }
        }
    };
</script>
```

**Comment by tmorehouse** [comment]
`b-form-input` currently fires a custom change` event which receives the inputs value as the first argument. the native event object is not passed.

To access the native `change` event, use the `@input.native="onChange"` format. This will receive the native change event as the first argument.

**Comment by Giwayume** [comment]
That was the *first* thing I tried, actually. Nether `@change="onChange"` nor `@change.native="onChange"` works. The input event does work, but that isn't the event I need.

Open this example in IE11:

https://jsbin.com/dawadideco/edit?html,output

**Comment by tmorehouse** [comment]
CLosing issue for now, as we think this may be fixed in the latest `dev` branch.

Feel free to open a new issue if you still experience the issue in the next release.

**Comment by cyrrill** [comment]
@tmorehouse I am experiencing this bug right now. The `@change` input event does not get fired:

`<b-form-input v-model="newName" :state="nameStatus" @change="nameChanged" />`

Could you verify this has been fixed in the merge you mentioned?

**Comment by Flecart** [comment]
the issue still exists, i have a form input that handles only numbers, if i write numbers in there the event does not fire, it fires when i click the arrows in the input field (but it should also fire when i change numbers by typing)
