### ISSUE TITLE
Tree shaking not working

### ISSUE THREAD

**Issue by cliffordh** [bootstrap-vue/bootstrap-vue#2513]
I have a minimal bootstrap-vue application. I basically just used the Vue CLI to create a new project, and added bootstrap-vue as follows:

```
import BootstrapVue from "bootstrap-vue";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-vue/dist/bootstrap-vue.css";
Vue.use(BootstrapVue);

```
I also added font-awesome but that doesn't appear to take up that much space...

When I perform a build using the Vue UI the build size seems enormous:

```
File                                   Size              Gzipped

  dist/js/chunk-vendors.efb23010.js      422.49 KiB        131.86 KiB
  dist/js/app.7c82e299.js                7.65 KiB          2.82 KiB
  dist/js/about.3a94e576.js              0.44 KiB          0.31 KiB
  dist/css/chunk-vendors.f1000a76.css    171.00 KiB        24.30 KiB
  dist/css/app.03795e02.css              0.53 KiB          0.31 KiB

```
I found another thread mentioning build size and it mentioned something about "esm" builds and I tried using a different import, but barely any difference:

`//import BootstrapVue from "bootstrap-vue/dist/bootstrap-vue.esm.min";`

Any suggestions? Thanks.

**Comment by mikeerickson** [comment]
Curious, how about using a CDN release which will likely always use a cached version of the framework.

**Comment by cliffordh** [comment]
Here's the visual output from source-map-explorer

<img width="1316" alt="screen shot 2019-02-04 at 9 31 51 am" src="https://user-images.githubusercontent.com/1755156/52214563-e88bf000-285f-11e9-8ef7-5cd8598fe604.png">

**Comment by hertz1** [comment]
Try importing like this:

```js
import Navbar from 'bootstrap-vue/es/components/navbar'
Vue.use(Navbar)
```

**Comment by cliffordh** [comment]
Thanks for responding. Unfortunately that does not make a difference. I'm using 2.0rc11. I'm going to try and register components individually to see if this helps. Could this be a bug in 2.0rc11?

**Comment by cliffordh** [comment]
Individually importing the components and registering them results in a massive reduction in the amount of code imported, from 160k to about 10k. I wouldn't call this issue closed because I shouldn't have to do this, but given these results I think I can still proceed with using bootstrap-vue.

```
import bNavbar from "bootstrap-vue/es/components/navbar/navbar";
import bNavbarNav from "bootstrap-vue/es/components/navbar/navbar-nav";
import bNavbarBrand from "bootstrap-vue/es/components/navbar/navbar-brand";
import bNavbarToggle from "bootstrap-vue/es/components/navbar/navbar-toggle";
import bNavItem from "bootstrap-vue/es/components/nav/nav-item";
import bCollapse from "bootstrap-vue/es/components/collapse/collapse";
import BLink from "bootstrap-vue/es/components/link/link";

```
```
Vue.component("b-navbar-toggle", bNavbarToggle);
Vue.component("b-navbar", bNavbar);
Vue.component("b-navbar-nav", bNavbarNav);
Vue.component("b-navbar-brand", bNavbarBrand);
Vue.component("b-nav-item", bNavItem);
Vue.component("b-link", BLink);
Vue.component("b-collapse", bCollapse);

```
<img width="221" alt="screen shot 2019-02-05 at 11 53 55 am" src="https://user-images.githubusercontent.com/1755156/52289812-be5c3000-293c-11e9-9cf7-f7eeb3fe6a79.png">

**Comment by mikeerickson** [comment]
Interesting results... what tool are you using to get the source map that you have been posting

**Comment by cliffordh** [comment]
@mikeerickson it's called source-map-explorer https://www.npmjs.com/package/source-map-explorer

**Comment by pi0** [comment]
> I shouldn't have to do this

Why?

BootstrapVue when used project-wide, cannot predict what components are going to be used on runtime. I'm working on nuxt module improvement to make it as easy at declaring needed components via `nuxt.config`, which can be easily used for a VueCLI too.

**Comment by pi0** [comment]
PS: Next release has side-effects field which can potentially allow using `import { } from ...` syntax.

**Comment by cliffordh** [comment]
The documentation here: https://bootstrap-vue.js.org/docs has a section: Individual components and directives, which states: "If you would like to only pull in a specific component or set of components, you can do this by directly importing those components."

Unfortunately, this does not work. That is why I said in an earlier comment, that "I shouldn't have to do this". @pi0 Hopefully the coming soon label indicates that a fix is in the works. Thanks!

**Comment by tmorehouse** [comment]
@cliffordh BootstrapVue v2.0.0-rc.12 was just released today.  COuld you see if there is any improvement for you?

**Comment by cliffordh** [comment]
@tmorehouse Tree shaking doesn't seem to be working... I'm getting table, card, carousel, tabs, etc. which I'm not using. However, my Bootstrap dropdown issue in Safari and the missing BSpinner has been fixed by RC12.

**Comment by tmorehouse** [comment]
Rc.11 never had b-spinner. It is new in rc.12.

Vue.use(plugin) has bootstrap vue install all components, and since they are referenced, webpack doesn't know if you are using sub components or not.

Importing BootstrapVue and then vue.use the sub component plugins (or components) from that reference should tree shake any unused components out.

**Comment by pimlie** [comment]
Is there maybe a verified example available where tree shaking works? Preferable in a Nuxt project?

I have a nuxt plugin with:
```js
// ./plugins/bootstrap-vue.js
import Vue from 'vue'
import {
  Badge,
  Breadcrumb,
  Button,
  Card,
  Collapse,
  FormInput,
  InputGroup,
  Layout,
  Link,
  Modal,
  Nav,
  Navbar,
  Tabs
} from 'bootstrap-vue/es/components/'

Vue.use(Badge)
Vue.use(Breadcrumb)
Vue.use(Button)
Vue.use(Card)
Vue.use(Collapse)
Vue.use(FormInput)
Vue.use(InputGroup)
Vue.use(Layout)
Vue.use(Link)
Vue.use(Modal)
Vue.use(Nav)
Vue.use(Navbar)
Vue.use(Tabs)
```
and in my `nuxt.config.js` I have
```js
  plugins: [
    '@/plugins/bootstrap-vue'
  ]
```

but unfortunately I still get carousel, jumbotron and all the other stuff I dont use. You would make me very happy if I can get my vendors bundle down to a more reasonable number then the `300KB` it is now (of which `212KB` is bootstrap-vue and `21KB` popper).

<sub>I tried to setup a [csb](https://codesandbox.io/s/j3o35x2899) but csb doesnt seem to work for me (cant change anything anymore suddenly and it doesnt want to rebuild)</sub>

**Comment by tmorehouse** [comment]
Try this:
```js
import Vue from 'vue'

import Badge from 'bootstrap-vue/es/components/badge'
import Breadcrumb from 'bootstrap-vue/es/components/breadcrumb'
import Button from 'bootstrap-vue/es/components/button'
// ...
import Tabs from 'bootstrap-vue/es/components/tabs'

Vue.use(Badge)
Vue.use(Breadcrumb)
Vue.use(Button)
// ...
Vue.use(Tabs)
```

**Comment by pimlie** [comment]
@tmorehouse Thank you, you are my hero of the day! :kiss: 

Now its only `163KB`
![image](https://user-images.githubusercontent.com/1067403/52980852-74635780-33dc-11e9-8315-cf1e435f89e8.png)

(I create the webpack analyzer reports with `nuxt build -a`, quick and easy and in production mode by default)
