### ISSUE TITLE
Dependency not found install regenerator-runtime/runtime

### ISSUE THREAD

**Issue by ChunAllen** [bootstrap-vue/bootstrap-vue#2674]
I just upgraded bootstrap-vue from `2.0.0-rc-11` to `2.0.0-rc-12` but when I run the app it ask me to install **regenerator-runtime/runtime**

<img width="750" alt="screenshot 2019-02-21 15 09 18" src="https://user-images.githubusercontent.com/2100728/53150107-aba75380-35ea-11e9-9dfd-b9c311162ce5.png">

then when I try to install `npm install --save regenerator-runtime/runtime` it returns error

<img width="753" alt="screenshot 2019-02-21 15 10 40" src="https://user-images.githubusercontent.com/2100728/53150161-dd201f00-35ea-11e9-9458-e2e6bcbfbcf5.png">

I'm currently using Nuxt 2.0.0

**Comment by jackmu95** [comment]
Please use the latest release 2.0.0-rc-13.

**Comment by ChunAllen** [comment]
@jackmu95 I also tried using rc-13 version and I'm still getting the same error

**Comment by jackmu95** [comment]
@ChunAllen The correct install command is `npm install --save regenerator-runtime`.

**Comment by ChunAllen** [comment]
Thanks @jackmu95. Now I'm getting `regeneratorRuntime is not defined` from browser's console. Did I miss something here?

**Comment by tmorehouse** [comment]
I think this will be fixed in 2.0.0-rc.14, as we have Babel include the runtime helpers in each `es` sub module where needed.

**Comment by tmorehouse** [comment]
should be fixed in the just released 2.0.0-rc.14

**Comment by ChunAllen** [comment]
I just updated 2.0.0-rc.14 but I'm still getting this 
<img width="1270" alt="Screenshot 2019-03-13 23 27 16" src="https://user-images.githubusercontent.com/2100728/54291477-902ad980-45e7-11e9-9176-155e5a468901.png">

did I miss something? I tried removing my node_modules and package-lock.json then npm install but I'm still getting error. 

Here's my package.json
```
{
  "name": "vs_admin",
  "version": "1.0.0",
  "description": "Frontend for VS App Admin",
  "author": "STB Tech Dev",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build --spa",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "mocha --recursive -r esm"
  },
  "dependencies": {
    "@johmun/vue-tags-input": "^2.0.1",
    "axios": "^0.18.0",
    "bootstrap-vue": "^2.0.0-rc.14",
    "chai": "^4.2.0",
    "config": "^3.0.1",
    "cookieparser": "^0.1.0",
    "cross-env": "^5.2.0",
    "esm": "^3.2.5",
    "faker": "^4.1.0",
    "jquery": "^3.3.1",
    "js-cookie": "^2.2.0",
    "mocha": "^6.0.1",
    "nuxt": "^2.4.3",
    "regenerator-runtime": "^0.13.1",
    "repl": "^0.1.3",
    "sinon": "^7.2.4",
    "vue-bootstrap-toggle": "^1.1.4",
    "vue-clamp": "^0.2.1",
    "vue-date-pick": "^1.1.0",
    "vue-loader": "^15.6.4",
    "vue-select": "^2.5.1",
    "vuedraggable": "^2.17.0",
    "vuejs-noty": "^0.1.3",
    "vuelidate": "^0.7.4"
  },
  "devDependencies": {
    "dotenv": "^6.2.0",
    "node-sass": "^4.10.0",
    "nodemon": "^1.18.10",
    "sass-loader": "^7.1.0"
  }
}
```

**Comment by yaniv51** [comment]
Hi, I'm getting the same error while updating 2.0.0-rc.11 to 2.0.0-rc.17 (and 16,15,14,13,12).
Package.json:
"dependencies": {
    "@nuxtjs/auth": "4.5.3",
    "@nuxtjs/axios": "5.4.1",
    "@nuxtjs/dotenv": "1.3.0",
    "@nuxtjs/toast": "3.0.2",
    "@nuxtjs/sitemap": "0.2.2",
    "bootstrap-vue": "2.0.0-rc.17",
    "eslint-loader": "2.1.2",
    "jquery": "3.3.1",
    "lodash": "4.17.11",
    "node-sass": "4.10.0",
    "nuxt": "2.5.1",
    "nuxt-device-detect": "1.1.4",
    "nuxt-sass-resources-loader": "2.0.5",
    "sass-loader": "7.1.0",
    "vue-i18n": "8.9.0",
    "vue-owl-carousel": "2.0.3"
  },
  "devDependencies": {
    "ava": "^0.19.1",
    "babel-eslint": "^8.2.1",
    "cross-env": "^5.2.0",
    "eslint": "^4.19.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-plugin-vue": "^4.7.1",
    "node-fetch": "^2.3.0",
    "puppeteer": "^1.13.0",
    "resize-observer-polyfill": "^1.5.1",
    "uglifyjs-webpack-plugin": "^2.1.2"
  },

After installing regenerator-runtime
>npm install --save regenerator-runtime

I'm getting error:
![bootstrap-vue-error](https://user-images.githubusercontent.com/10440710/55706581-37820d00-59ea-11e9-8387-a1c690d1cb97.JPG)
