### ISSUE TITLE
Dropdown regression on from version 0.15

### ISSUE THREAD

**Issue by MarZab** [bootstrap-vue/bootstrap-vue#362]
I've got a bug on all my dropdowns from version 0.15; Clicking anything makes all the options active and does not complete the action. The dropdown is unresponsive afterwards.

![snip_20170508173419](https://cloud.githubusercontent.com/assets/1311249/25828764/553c93b6-3452-11e7-80a4-c5e9ca218c67.png)

**Comment by tmorehouse** [comment]
Could you provide a bit of sample code, or a jsfiddle? Is this embedded in a nav? and which flavour of the dropdown are you using? `b-nav-dropdown-item`, `b-dropdown`, or `b-button-group-dropdown`

**Comment by MarZab** [comment]
Latest packages, stock bootstrap latest 4 and this:

`// global css

import "./main.scss"

import Vue from 'vue'
import VueRouter from 'vue-router'
Vue.use(VueRouter);

// bootstrap
import BootstrapVue from 'bootstrap-vue';
Vue.use(BootstrapVue);

// router
let routes = [
    {
        name: 'dsf',
        path: '',
        component: {
            'template': `<b-dropdown text="Dropdown" variant="success" class="m-md-2">
        <b-dropdown-header>This is a heading</b-dropdown-header>
        <b-dropdown-item>Action</b-dropdown-item>
        <b-dropdown-item>Another action</b-dropdown-item>
        <b-dropdown-divider></b-dropdown-divider>
        <b-dropdown-item>Something else here...</b-dropdown-item>
    </b-dropdown>`
        }
    },

];
let router = new VueRouter({routes:routes});

/* eslint-disable no-new */
let vueinstance = new Vue({
    el: '#app',
    router: router,
});
`

removing vue-router fixes the issue.

**Comment by MarZab** [comment]
Fiddle: https://jsfiddle.net/7htvb7gh/1/

**Comment by tmorehouse** [comment]
In the fiddle I see the following menu generated:
```html
<div role="menu" class="dropdown-menu">
 <h6 tabindex="-1" class="dropdown-header">This is a heading</h6>
 <a href="/7htvb7gh/1/show/#" class="active dropdown-item" aria-disabled="false" tabindex="-1" role="menuitem">Action</a>
 <a href="/7htvb7gh/1/show/#" class="active dropdown-item" aria-disabled="false" tabindex="-1" role="menuitem">Another action</a>
 <div role="separator" class="dropdown-divider"></div>
 <a href="/7htvb7gh/1/show/#" class="active dropdown-item" aria-disabled="false" tabindex="-1" role="menuitem">Something else here...</a>
</div>
```
If you notice, each `<a href="...">`is pointing to the same URL.  vue-router is setting the active-class on all of them, since they are all technically pointing to the same destination route.

Do you intend the links to be each pointing to a different `to` or `href`?

It looks like when no `href` or `to` field is given to `b-dropdown-item`, that it is turning into a `router-link`

**Comment by MarZab** [comment]
> It looks like when no href or to field is given to b-dropdown-item, that it is turning into a router-link

So I've been using the dropdown with only click events, not for navigation at all.

**Comment by tmorehouse** [comment]
I think this might be a bug in how b-link is generating the link reference (href & to) and selecting the component type (router-link or b-link).

I'll try mocking up a fiddle with an altered `b-nav-link` component and see what I can figure out.

**Comment by tmorehouse** [comment]
@MarZab , this issue should be addressed in the next release.

**Comment by MarZab** [comment]
I've tried the latest in the trunk but looks like b-dropdown-item is still not usable for non-navigation, @ click does not work.

I would really expect dropdown-item to not be just for naviagion, am I wrong on this?
