### ISSUE TITLE
Error: "Uncaught TypeError: t.includes is not a function"

### ISSUE THREAD

**Issue by valexiev** [bootstrap-vue/bootstrap-vue#587]
Thank you for the new release!

I've just updated bootstrap-vue to 0.17.0 and when I run the project an error is thrown:
"Uncaught TypeError: t.includes is not a function", pointing to bootstrap-vue.esm.js.

Does anybody else have the same error?
Any suggestion for fixing it?

**Comment by alexsasharegan** [comment]
Did it give you any line # column #? This sounds like Array.prototype.includes is in the source, and is not transpiled. What browser vendor and version were you using to produce the error?

**Comment by alexsasharegan** [comment]
I believe I have found all the uses of `Array.prototype.includes` in the source. Bublé (transpiler) is more opinionated than babel, and does not transpile this. PR coming shortly.

**Comment by alexsasharegan** [comment]
@tmorehouse, you don't think this will make it into 0.17.1?

**Comment by tmorehouse** [comment]
0.17.1 is already out :smile:

**Comment by alexsasharegan** [comment]
Haha, then I think you're right!

**Comment by alexsasharegan** [comment]
Fix is in PR #589

**Comment by valexiev** [comment]
Thanks for the prompts responses!

The browser is Chromium v46.

In the /dist/bootstrap-vue.esm.js this is the only occurrence of t.includes:
`function omitLinkProps() {
	for (var t = [], e = arguments.length; e--;) t[e] = arguments[e];
	return Object.keys(props).reduce(function(e, n) {
		return t.includes(n) || (e[n] = props[n]), e
	}, {})
}`

**Comment by alexsasharegan** [comment]
Thanks for the update! Confirms my suspicions. Fix is merged and will appear in `v0.17.2`.

**Comment by tmorehouse** [comment]
I'll close this issue.

v0.17.2 should be available soon.

**Comment by invergent** [comment]
It's 2019, I am still getting the same error **"TypeError: t.includes is not a function"**. Although, there is a bit of a twist to it. I only get the error when using a mobile device to access the app.

**Comment by tmorehouse** [comment]
@invergent what version are you using, and what browser?  if using IE mobile (or other older browsers), make sure you are using the latest polyfils.
