### ISSUE TITLE
Radio button throws "Uncaught TypeError: this.checked.includes is not a function"

### ISSUE THREAD

**Issue by wsw70** [bootstrap-vue/bootstrap-vue#623]
I tried (https://codepen.io/WoJWoJ/pen/YQLqjG) the simplest radio button (includes per the documentation):

```
<div id="root">
  <b-form-checkbox v-model="selected">something</b-form-checkbox>
  <div>
    The checkbox is selected: {{selected}}
  </div>
</div>
```

```
new Vue ({
  el: "#root",
  data: {
    selected: true
  }
})
```

The output is

```
something
The checkbox is selected: {{selected}}
```

and the Chrome DevTools show

```
vue.min.js:6 Uncaught TypeError: this.checked.includes is not a function
    at a.isChecked (form-checkbox.vue:43)
    at no.get (vue.min.js:7)
    at no.evaluate (vue.min.js:7)
    at a.isChecked (vue.min.js:6)
    at a.render (form-checkbox.vue:24)
    at a.n._render (vue.min.js:6)
    at a.<anonymous> (vue.min.js:6)
    at no.get (vue.min.js:7)
    at new no (vue.min.js:7)
    at a.e._mount (vue.min.js:6)
```

**Comment by tmorehouse** [comment]
Which Bootstrap-Vue version are you using? v0.17.1?

**Comment by wsw70** [comment]
@tmorehouse: I wanted to add this information (also to my previous bug) but I do not know how to find out which version is used. I included the files per the documentation:

```
<!-- Add this to <head> -->
<link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap@next/dist/css/bootstrap.min.css"/>
<link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css"/>

<!-- Add this after vue.js -->
<script src="//unpkg.com/babel-polyfill@latest/dist/polyfill.min.js"></script>
<script src="//unpkg.com/tether@latest/dist/js/tether.min.js"></script>
<script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>
```

**Comment by tmorehouse** [comment]
OK, you are using the latest (which is v0.17.1)

**Comment by tmorehouse** [comment]
This should be fixed in the latest master, which will be in release v0.18.0

**Comment by tmorehouse** [comment]
A current quick workaround is to use the babel polyfil on the client.

**Comment by sushain97** [comment]
I'm also encountering this problem but Babel polyfill doesn't fix it unfortunately.

**Comment by tmorehouse** [comment]
The current issue is with `Array.prototype..includes`, which is not available in all browsers.

Release v.0.18.0 should be available in the next couple of days.

**Comment by sushain97** [comment]
> The current issue is with Array.prototype.includes, which is not available in all browsers.

Hm, I'm not in such a browser:

```js
[].includes
function includes() { [native code] }
```

(using Chrome 59)

Using the Chrome debugger, I get that `this.checked` is `false` rather than an `Array`, hence the problem. My usage is:

```
<b-form-fieldset horizontal label="&nbsp;" :feedback="fieldErrors('closed')" :state="fieldState('closed')">
    <b-form-checkbox v-model="closed" class="text-left">Closed</b-form-input>
</b-form-fieldset>
```

with 

```js
 data: () => ({
    // unrelated stuff
    closed: false,
}),
```

Doing `closed: [false],` instead fixes the problem.

Perhaps I'm using `<b-form-checkbox>` wrong? I've only been using Vue for a couple days :)

**Comment by tmorehouse** [comment]
What v-bind variable type are you providing to checkbox?

If it is an array it should return an array (assuming multiple checkboxes bound to the same variable)., if it is scalar (boolean or string) it should return the single value (assuming only one check box bound to the variable).

**Comment by tmorehouse** [comment]
We're hoping to make b-checkbox similar to b-radio, where you can provide an array of "options" to create a series of checkboxes.  But that features probably wont be available until release 0.19.0 or 0.20.0

**Comment by sushain97** [comment]
> What v-bind variable type are you providing to checkbox?

I may be misunderstanding your question but it is not a boolean from my above snippet since `data.closed` is `false` and `v-model="closed"`?

> assuming only one check box bound to the variable

Indeed, there is only one check box on my page in general.

**Comment by tmorehouse** [comment]
OK, I think I have found the issue.

**Comment by sushain97** [comment]
@tmorehouse thanks! I'll `yarn add` master here after your PR gets merged.

**Comment by tmorehouse** [comment]
@sushain97 The PR has been merged into master, so give it a whirl.

**Comment by tmorehouse** [comment]
@sushain97 @wsw70 

Release v0.18..0 is now available (latest), and this issue *should* be resolved.

**Comment by sushain97** [comment]
I can verify that it is once again working as expected. Thanks for the help, @tmorehouse!

**Comment by mgrollins** [comment]
Was it a lack of "v-bind" usage causing the Boolean value to be converted to a string "false"?

I've run into this recently and have finally found a reason for it in the guide documentation! The issue is the if the Vue "v-bind" directive (or short-cut of colon ":") is not added to "value" attribute of the radio button, the Boolean `false` value is converted to the string 'false' after a few transitions of the radio button group! Since "false" === false, the readonly attribute is applied to the element when it shouldn't be!!!

> ...V-bind forces Vue to treat as JavaScript expression rather than a string...

```
<!-- Even though `42` is static, we need v-bind to tell Vue that -->
<!-- this is a JavaScript expression rather than a string.       -->
<blog-post v-bind:likes="42"></blog-post>

<!-- Dynamically assign to the value of a variable. -->
<blog-post v-bind:likes="post.likes"></blog-post>
```
[Guide - Props](https://vuejs.org/v2/guide/components-props.html#Passing-a-Number)

This change from a Boolean (not surrounded by quotes) to a String (surrounded by quotes) is visible in Vue devtools!
