### ISSUE TITLE
[nav-item-dropdown] search box with result dropdown

### ISSUE THREAD

**Issue by pimlie** [bootstrap-vue/bootstrap-vue#645]
I am trying to add a search box in my menu bar with a popover dropdown menu. Unfortunately because of the a-tag that's always there I am getting some unexpecting results.

My current template is:
```html
<b-nav class="pull-right">
  <b-nav-item-dropdown right noCaret>
    <b-input-group slot="button-content">
      <b-form-input slot="left" v-model="searchText" placeholder="search"></b-form-input>
     
      <div slot="right" class="btn btn-primary"><i class="fa fa-search"></i></div>
    </b-input-group>

    <b-popover>
      <div >
        <b-dropdown-header>no results found</b-dropdown-header>
      </div>
    </b-popover>
  </b-nav-item-dropdown>
</b-nav>
```
which looks like
![image](https://user-images.githubusercontent.com/1067403/27857884-95d87f90-6173-11e7-99cd-63a2e0f9f8ff.png)

Using the git version of bootstrap-vue this all works mostly well, except that now when I click in the input field to enter my search terms, the popup is immediately opened and focus is set on the dropdown-menu. This means I can't type anything in the search box unless I click the input field again. Any recommendations what the best way to solve this?

**Comment by tmorehouse** [comment]
The `text` slot (now superseded by the `button-content` slot), is the content that goes in the dropdown button (or in the case an `<a>` tag).  Basic HTML issupported (bold, splan, em, etc), but that contat will always be placed in the A-Tag.

Your best bet would be to place an input group directly in the navabr, and use the input group addon and place your dropdown in the right slot.  

```html
<b-nav-form>
  <b-input-group>
    <b-form-input v-model="searchText" placeholder="search">/b-form-input>
    <template slot="right" text="<i class=\"fa fa-search\"></i>">
      <b-dropdown right ref="dropdown_content">
        <b-dropdown-header>no results found</b-dropdown-header>
      <b-dropdown>
  </b-input-group>
</b-nav-form>
```

**Comment by pimlie** [comment]
Thanks for the help. Unfortunately it seems this trick doesnt work for me, see image below
![image](https://user-images.githubusercontent.com/1067403/27874742-e60abdd8-61b0-11e7-888b-4e8218f006e6.png)

It ignores the noCaret and it doesnt accept the `<i>` in text, in the final html source it's only listed as `&quot;&gt;&quot;&gt;`. 

I've got it working now by using a custom component which imports the clickout & dropdown mixins. Instead of using `<b-dropdown` I have copied the `<div ref="menu" role="menu"...` tag to my component, not an elegant solution but it works :sweat_smile:

**Comment by tmorehouse** [comment]
Had a mistake in the example above.  Corrected here:

```html
<b-nav-form>
  <b-input-group>
    <b-form-input v-model="searchText" placeholder="search">/b-form-input>
    <b-input-group-addon slot="right">
      <b-dropdown right noCaret  text="<i class=\"fa fa-search\"></i>">
        <b-dropdown-header v-if="results.length === 0">no results found</b-dropdown-header>
        <b-dropdown-item v-else v-for="res in results">{{ re.content}}</b-dropdown-item>
      <b-dropdown>
    </b-input-group-addon>
  </b-input-group>
</b-nav-form>
```

**Comment by tmorehouse** [comment]
@pimlie Check the updated example above.  `no-caret` is only applicable to `b-nav-item-dropdown`

**Comment by pimlie** [comment]
Thanks again for your help. Unfortunately that solution is still not sufficient:
![image](https://user-images.githubusercontent.com/1067403/27903971-7b4062ce-623b-11e7-80c1-bf1a64c78159.png)

By adding a `list-style-type: none` style and a `p-0` class on the group-addon I can get it to look like this:
![image](https://user-images.githubusercontent.com/1067403/27904030-a71d2594-623b-11e7-94b1-2a0854b33c01.png)

But then still we have the following issues:
- you cant set the group-addon to a 'primary' variant. The a.nav-link color is also primary and without extra css you cant overrule that colour
- more importantly, it seems there is no way to programmatically open the dropdown when you type in form-input. I believe a key feature of a searchbox is that the results are shown immediately when you start typing, but I can't access the `visible` data property of the dropdown mixin from here.
- the generated html is a bit 'off' with that `li` tag hanging there:
```html
<form class="hidden-xs-down pull-right search-menu form-inline">
  <div role="group" class="input-group">
    <!---->
    <input type="text" placeholder="search" value="" class="form-control">
    <div class="input-group-addon p-0">
      <li class="nav-item dropdown show" style="list-style-type:none;">
        <a href="#" aria-haspopup="true" aria-expanded="true" class="nav-link">
          <span class="sr-only">Search Results</span>
          <i aria-hidden="true" class="fa fa-search"></i>
        </a>
        <div role="menu" class="dropdown-menu dropdown-menu-right">
          <h6 tabindex="-1" class="dropdown-header active">no results found</h6>
        </div>
      </li>
    </div>
  </div>
</form>
```
The following custom component does seem to do the trick for me:
```js
<template>
  <div :class="['dropdown','btn-group',{dropup, show: visible}]">
    <b-input-group>
      <b-form-input slot="left" v-model="searchText" placeholder="search"
       @keyup.esc="onEsc"
       @keydown.tab="onTab"
        ></b-form-input>

      <b-input-group-button slot="right">
        <b-button variant="primary" @click="toggle"><i class="fa fa-search"></i></b-button>
      </b-input-group-button>
    </b-input-group>

    <div :class="['dropdown-menu',{'dropdown-menu-right': right}]"
         ref="menu"
         role="menu"
         @keyup.esc="onEsc"
         @keydown.tab="onTab"
         @keydown.up="focusNext($event,true)"
         @keydown.down="focusNext($event,false)"
         @mouseover="focusHovered($event)"
         style="width: 200%"
    >
      <b-dropdown-header v-if="results.length === 0">no results found</b-dropdown-header>
      <b-dropdown-item v-else v-for="res in results" :key="res" :href="res.href">
          {{ res.content }}
      </b-dropdown-item>
    </div>
  </div>
</template>
<script>
import clickOut from '../node_modules/bootstrap-vue/lib/mixins/clickout.js'
import dropdown from '../node_modules/bootstrap-vue/lib/mixins/dropdown.js'

export default {
  mixins: [
    clickOut,
    dropdown
  ],
  data () {
    return {
      visible: false,
      results: []
    }
  },
  watch: {
    searchText () {
      this.search()
    }
  },
  methods: {
    clickOutListener () {
      console.log(this.categories)
      this.visible = false
    },
    search () {
      this.visible = true
      // get results from api
    }
  }
}

**Comment by tmorehouse** [comment]
Yeah, It might be best that you generate a custom component for this type of application, rather than use one of the dropdown flavours, which were designed primarily as menus (which have keyboard navigation features which rely on a particular structure and set of subcomponents)., and nav-item-dropdown typically expects itself to be a direct child of a nav or navbar (based on BS V4 CSS).

But I think you are off to  good start.  I'm curious as to how it works when the navbar collapses on smaller screens (or is your navbar non-collapsing)?

**Comment by pimlie** [comment]
> I'm curious as to how it works when the navbar collapses on smaller screens

For smaller screens I remove the whole search box from the navbar, I couldnt find a nice solution for a small screen myself. After looking at what others do I think that removing the search bar for small screens is the consensus here. Only have to find a better solution for the `width: 200%`, maybe in the end I will add some styles for that to make it work on different screen sizes.

Thanks again for looking at this with me!

**Comment by tmorehouse** [comment]
Glad we could help out some!
