### ISSUE TITLE
Documentation Not Opening / Broken Documentation Link

### ISSUE THREAD

**Issue by Hossein-Mirazimi** [bootstrap-vue/bootstrap-vue#7231]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.
https://bootstrap-vue.org/

![Image](https://github.com/user-attachments/assets/550af7db-1721-4fd3-b39e-bd3bda719fed)

**Comment by albertbenitez** [comment]
Wonder if we can download a copy of the website to run locally. Any ideas?

**Comment by Animus-Surge** [comment]
The link in the README.md needs to be updated to switch to the github pages links. Here is a direct link: https://bootstrap-vue.github.io/bootstrap-vue/

**Comment by illmaren** [comment]
This won't fix the Documentation to 100%.

The Search is redirecting a bit wrong, its removing the second bootstrap-vue from the link generation
https://bootstrap-vue.github.io/bootstrap-vue/ to https://bootstrap-vue.github.io/

**Comment by matheus-rodrigues00** [comment]
> The link in the README.md needs to be updated to switch to the github pages links. Here is a direct link: https://bootstrap-vue.github.io/bootstrap-vue/

Also, the Google search engine shows the old website, probably should have a redirect or SEO improvement on the new version

**Comment by Saayanel** [comment]
> The link in the README.md needs to be updated to switch to the github pages links. Here is a direct link: https://bootstrap-vue.github.io/bootstrap-vue/

Also, the right side menu links are missing a part of the path:

![Image](https://github.com/user-attachments/assets/319b0bc0-a143-463c-ad7b-a0ccd3b32ced)

Edit: links inside the pages are wrong too:

![Image](https://github.com/user-attachments/assets/e6496a88-a731-4ea0-9661-3159931dbc94)

**Comment by Animus-Surge** [comment]
I'll go through the docs and see what I can find that's broken. As for the SEO I'm not entirely sure how to go about fixing this, but most likely it's something to do with hosting which I can't fix on my end and will have to defer that to the project contributors.

**Comment by zcoop98** [comment]
Something seems to have changed since this was first raised; initially, the original domain was just broken-- you had to use `https://bootstrap-vue.github.io/bootstrap-vue/`. 

This now redirects back to the old `bootstrap-vue.org` domain, but the documentation header links remain broken; they have _no_ path now (just the hashes `#`):

> ![Image](https://github.com/user-attachments/assets/ae62de3f-a646-4cf1-854f-b00c1bfd6d33)

**Comment by Animus-Surge** [comment]
I believe the documentation here should be fixed as of #7251. When I opened my PR I got a comment a couple days later saying that the primary domain for the project is back up, which is why the link I gave earlier here now redirects. Those hash links in the `<a>` tags represent in-page links that let you navigate between sections without loading a completely new webpage (for those curious, known as anchor references).

It's confusing because my browser isn't showing the current webpage when hovering over these links. For example, instead of `https://bootstrap-vue.org/docs/components/form-group#accessibility` it instead shows me `https://bootstrap-vue.org/#accessibility` even though the links do actually work as intended and navigate to the correct section on the current page. I wouldn't know where to begin looking for that bug though

**Comment by zcoop98** [comment]
Something still isn't right with how links and navigation are being handled, and there are still a few outstanding issues.

As called out a month ago [above](https://github.com/bootstrap-vue/bootstrap-vue/issues/7231#issuecomment-2768529193), the actual `href` locations in the righthand-sidebar nav anchors are still incorrect. When clicked, all links except the top-most header work properly (clicking the top one sends you back to the `https://bootstrap-vue.org/` homepage), but they're not pointing to the right places.

Second, [the Table component page](https://bootstrap-vue.org/docs/components/table) has some sort of rendering issue when navigated to directly. Only the component reference section shows up, and no righthand-sidebar nav appears:

![Table component docs page with empty right sidebar and the usual page content after the introduction summary missing](https://github.com/user-attachments/assets/74c18c12-b9a1-4429-a69d-f9abb6cd333c)

This also generates console errors:

![2 JS console errors](https://github.com/user-attachments/assets/38285fb2-2321-4daa-86a2-b239e474d884)

> TypeError: Cannot read properties of undefined (reading 'tagName') – e19850c.modern.js:2
> 
> HierarchyRequestError: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
